on:
    workflow_call:
        inputs:
            base-url:
                description: 'URL where the app is running'
                required: true
                type: string

jobs:
    cypress-run:
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: ./.github/actions/setup-node
              with:
                  node-version: '20.x'
                  environment: 'dev'

            - name: Run Cypress tests
              run: |
                  npx cypress@13.15.0 run --env BASE_URL=${{ inputs.base-url }}
