on:
    workflow_call:

jobs:
    lint-code:
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Nodejs
              uses: ./.github/actions/setup-node
              with:
                  node-version: '20.x'
                  environment: 'dev'

            - name: Lint
              run: |
                  npm run lint
