on:
    workflow_call:
        inputs:
            environment:
                description: environment to deploy to
                required: true
                type: string

jobs:
    tag_stable:
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v4
            - name: Creating stable tag as it is correctly deployed
              run: |
                  tag_name="stable-${{inputs.environment}}-$(date +'%Y%m%d%H%M%S')"
                  git tag $tag_name
                  git push origin $tag_name
